### ISSUE TITLE
use db name in health check

### ISSUE THREAD

**Issue by 23will** [gokhansengun/Docker-Hub-Flyway-Postgres#2]
it would be nice not be as restricted and be able to create the db in docker compose, i.e. 

```
version: '2'

services:

  postgres-db:
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user                                                                                                        
      - POSTGRES_DB=test_db 

  flyway-migrator:
    image: gsengun/flyway-postgres
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres-db
    command: postgres-db 5432 user secret test_db public
```

this would involve adding the `-d "$database_name"` param to the `psql` command in https://github.com/gokhansengun/Docker-Hub-Flyway-Postgres/blob/master/run-flyway.sh#L14
